### ISSUE TITLE
cache cargo binaries in git actions

### ISSUE THREAD

**Issue by dakom** [jewish-interactive/ji-cloud#17]
See: https://github.community/t/how-to-cache-cargo-binaries/17605/2

Specifically, cargo-make is a slow install

**Comment by dakom** [comment]
Another option is to download the official release, and that way we can pin it or have it always run the latest-and-greatest. Here's an example I had for doing that with `binaryen`:

```
- name: download binaryen release
  run: curl -u dakom:"$GITHUB_TOKEN" -s https://api.github.com/repos/WebAssembly/binaryen/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | xargs -I {} wget -c https://github.com/WebAssembly/binaryen/releases/latest/download/binaryen-{}-x86_64-linux.tar.gz -O binaryen.tgz
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
- name: extract binaryen to folder 
  run: mkdir binaryen && tar -zxvf ./binaryen.tgz -C binaryen --strip-components 1
- name: add binaryen to path
  uses: dakom/actions-path@master
  with:
    path: ${{github.workspace}}/binaryen
```
